version: "3"
services:
    web:
        build: ./.docker/php
        restart: always
        volumes:
        - ./:/var/www/html:delegated
        ports:
        - ${APACHE_PORT}:80
        env_file: .env
        environment:
            SYMFONY_ENV: "${SYMFONY_ENV}"
            PHP_IDE_CONFIG: "${PHP_IDE_CONFIG}"
            APACHE_RUN_USER: "www-data"
            APACHE_RUN_GROUP: "www-data"
    db:
        build: ./.docker/db
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: redbelts_test
        ports:
          - "${MYSQL_PORT_EXTERNAL}:3306"
